src/components/FlickityCarousel.js

* Move styled component outside render function

Move styled component outside render function

---

gatsby-config.js
package-lock.json
package.json

Added gatsby-plugin-styled-components for optimal SSR

Styled components fix

---

src/components/Carousel.js
src/components/HeadingWithBody.js
src/pages/apply.js
src/pages/techforbetter.js

Overflow hidden on application carousels

---

README.md

Relates #64 
Would be great to get feedback from @rebeccaradding on the content and suggested contributing process :)

First draft of README.md

---

src/components/SplashPhoto.js
src/pages/index.js

- Video Loop on home page
- Animation so it appears to grow as you scroll - closes #48 
- Fixed issue with splash images on extra large screens
At the moment we are serving the video (its 25MB) - I will look at load times and see if we want to serve it through video hosting service (youtube or vimeo)

Video homepage

---

src/components/Carousel.js
src/components/Step.js
src/components/StudentApplicationSteps.js
src/pages/apply.js
src/pages/index.js
src/pages/techforbetter.js
src/styles/index.css

Adjusted length of carousels to continue scroll at right point

---

src/assets/icons/heart.svg
src/components/Card.js
src/components/Panel.js

Closes #186 
closes #188 
closes #168

Photo links, preloading images and heart

---

src/components/DoubleLine.js
src/components/StudentApplicationSteps.js
src/components/StudentFAQs.js
src/maintenance.js
src/pages/about.js
src/pages/apply.js
src/pages/hire.js
src/pages/index.js
src/pages/stories.js
src/pages/techforbetter.js

Copy changes, extracting out T4B, added joe's form

---

package.json
src/components/Carousel.js
src/components/Cursor.js
src/components/DoubleLine.js
src/components/HeadingWithBody.js
src/components/Layout.js
src/components/Menu.js
src/components/Step.js
src/components/StudentFAQs.js
src/pages/about.js
src/pages/apply.js
src/pages/hire.js
src/pages/index.js
src/pages/stories.js
src/pages/techforbetter.js
src/styles/utils.js

* Add smooth video animation
* Use style prop for scroll animations for smoother rendering
* Do not show cursor when menu is open
* Add double line animation to pages
relates #53 
resolves #47

Smooth video

---

src/components/HeadingWithBody.js
src/components/Menu.js
src/styles/_custom.css

- Fix missing header nav on tablet
- Fix z index and fixed position of mobile nav
- fixed weird overflow issue except on tablet on page 2

mobile and tablet bug fixes

---

gatsby-config.js
src/components/Card.js
src/components/Panel.js
src/pages/apply.js
src/pages/techforbetter.js
src/storyData.js

+ Add Full Stop to copyright statement
+ Change all instances of "Founders & Coders" to "Founders and Coders"
+ Remove "Step #" copy in TechforBetter steps
+ Remove final spaces before closing quotation mark in testimonial cards
+ Make "Programme" lowercase in all instances of the techforbetter page
+ Lowercase staff titles (except for first letter)
+ Gaza cohort amended to reflect reality
Resolves #204 
resolves #231 
resolves #230 
resolves #228 
resolves #216 
resolves #208 
resolves #206

Pre-launch amendments: content

---

src/components/Header.js
src/components/Menu.js

+ Remove breaking right margin on topnav (Relates #209)
+ raise sticky menu triangle (?) to above open menu (Relates #229, #217)

Margins and sticky menu triangles

---

src/components/Header.js
src/components/Layout.js
src/components/Menu.js

- adds focus effect to nav bar items
- sets display none to menu when not active so it doesn't disrupt tab order 
relates #201 
again, thanks @oliverjam!

tab focus issues

---

src/components/Header.js
src/components/HomeLogo.js

+ Fix TopLink so an active link doesn't expand to 100% of remaining space
+ Correctly displaying topnav on 1040px width exactly
Relates #201, #209

TopNav fixes

---

src/pages/about.js

Display StaffCards properly on evil 1040px viewport

---

README.md

Line breaks on labels - relates #132

Tiny stuff

---

src/storyData.js

Corrects workbird to workerbird

Corrects workbird to workerbird

---

src/components/Panel.js

Ref https://github.com/foundersandcoders/hq/issues/338

De-ampersands fac linkedin link

---

src/components/Menu.js

* Fix overspilling menu on mobile

Fix overspilling menu on mobile

---

package-lock.json
package.json
src/components/Cursor.js
src/components/HomeLogo.js
src/components/Layout.js
src/components/Question.js

* Adjust FAC logo dimensions
* Update npm packages
* Improve question animations

Dropdown question animations

---

src/maintenance.js

remove year, fixes #238 but doesn't improve readability

fix application dates

---

src/pages/techforbetter.js

Correct spelling of Intersticia on TfB page

---

src/components/Menu.js

* Fixes issue where navbar appears on top of slide out menu
resolves #298

Fix z-index issues with mobile navbar & menu

---

src/components/StudentFAQs.js

Update StudentFAQs with more location info

---

src/pages/techforbetter.js

Change to TfB strapline

---

src/pages/techforbetter.js

Remove "programme" from the TfB page heading

---

package-lock.json
src/maintenance.js

open summer 2019 application

---

src/components/Header.js
src/components/Menu.js

change nav text both to about for consistency

---

src/components/HeadingWithBody.js
src/pages/404.js

Fix 404 page on desktop and mobile

---

src/components/partner_logos.js

comment out partner logos

---

src/pages/apply.js

update winter prereqs

---

src/pages/apply.js

fix JavaScript

---

src/maintenance.js

open winter application

---

src/components/Question.js

I forgot to do this when I made them not-collapsible
Fixes #365

Remove pointer cursor from all Questions

---

src/maintenance.js

close winter 2019

---

src/maintenance.js
src/pages/apply.js

update winter dates

---

src/maintenance.js

open spring 2020

---

src/pages/slack.js

No idea why it was working locally

Hopefully get the font working on /slack
